#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

# pr:1234 remains 2.2h
# Commit message
# 
# Detail Information

prline=$(grep -i '^pr:[0-9]\+\sremains [0-9]\{,2\}\(\.[0-9]\)\?h\s*$' "$1")
[ -n  "$prline" ] || {
	echo >&2 Message must start with such format as pr:1234 remains 2.5h
    exit 1
}
